__attribute__((visibility("default"))) void vkAcquirePerformanceConfigurationINTEL() {}
__attribute__((visibility("default"))) void vkAcquireProfilingLockKHR() {}
__attribute__((visibility("default"))) void vkAntiLagUpdateAMD() {}
__attribute__((visibility("default"))) void vkBindAccelerationStructureMemoryNV() {}
__attribute__((visibility("default"))) void vkBindDataGraphPipelineSessionMemoryARM() {}
__attribute__((visibility("default"))) void vkBindOpticalFlowSessionImageNV() {}
__attribute__((visibility("default"))) void vkBindTensorMemoryARM() {}
__attribute__((visibility("default"))) void vkBindVideoSessionMemoryKHR() {}
__attribute__((visibility("default"))) void vkBuildMicromapsEXT() {}
__attribute__((visibility("default"))) void vkCmdBeginConditionalRenderingEXT() {}
__attribute__((visibility("default"))) void vkCmdBeginQueryIndexedEXT() {}
__attribute__((visibility("default"))) void vkCmdBeginTransformFeedbackEXT() {}
__attribute__((visibility("default"))) void vkCmdBeginVideoCodingKHR() {}
__attribute__((visibility("default"))) void vkCmdBindDescriptorBufferEmbeddedSamplers2EXT() {}
__attribute__((visibility("default"))) void vkCmdBindDescriptorBufferEmbeddedSamplersEXT() {}
__attribute__((visibility("default"))) void vkCmdBindDescriptorBuffersEXT() {}
__attribute__((visibility("default"))) void vkCmdBindDescriptorSets2() {}
__attribute__((visibility("default"))) void vkCmdBindDescriptorSets2KHR() {}
__attribute__((visibility("default"))) void vkCmdBindIndexBuffer2() {}
__attribute__((visibility("default"))) void vkCmdBindIndexBuffer2KHR() {}
__attribute__((visibility("default"))) void vkCmdBindInvocationMaskHUAWEI() {}
__attribute__((visibility("default"))) void vkCmdBindPipelineShaderGroupNV() {}
__attribute__((visibility("default"))) void vkCmdBindShadersEXT() {}
__attribute__((visibility("default"))) void vkCmdBindShadingRateImageNV() {}
__attribute__((visibility("default"))) void vkCmdBindTransformFeedbackBuffersEXT() {}
__attribute__((visibility("default"))) void vkCmdBindVertexBuffers2() {}
__attribute__((visibility("default"))) void vkCmdBindVertexBuffers2EXT() {}
__attribute__((visibility("default"))) void vkCmdBlitImage2() {}
__attribute__((visibility("default"))) void vkCmdBlitImage2KHR() {}
__attribute__((visibility("default"))) void vkCmdBuildAccelerationStructureNV() {}
__attribute__((visibility("default"))) void vkCmdBuildAccelerationStructuresIndirectKHR() {}
__attribute__((visibility("default"))) void vkCmdBuildAccelerationStructuresKHR() {}
__attribute__((visibility("default"))) void vkCmdBuildMicromapsEXT() {}
__attribute__((visibility("default"))) void vkCmdControlVideoCodingKHR() {}
__attribute__((visibility("default"))) void vkCmdConvertCooperativeVectorMatrixNV() {}
__attribute__((visibility("default"))) void vkCmdCopyAccelerationStructureKHR() {}
__attribute__((visibility("default"))) void vkCmdCopyAccelerationStructureNV() {}
__attribute__((visibility("default"))) void vkCmdCopyAccelerationStructureToMemoryKHR() {}
__attribute__((visibility("default"))) void vkCmdCopyBuffer2() {}
__attribute__((visibility("default"))) void vkCmdCopyBuffer2KHR() {}
__attribute__((visibility("default"))) void vkCmdCopyBufferToImage2() {}
__attribute__((visibility("default"))) void vkCmdCopyBufferToImage2KHR() {}
__attribute__((visibility("default"))) void vkCmdCopyImage2() {}
__attribute__((visibility("default"))) void vkCmdCopyImage2KHR() {}
__attribute__((visibility("default"))) void vkCmdCopyImageToBuffer2() {}
__attribute__((visibility("default"))) void vkCmdCopyImageToBuffer2KHR() {}
__attribute__((visibility("default"))) void vkCmdCopyMemoryIndirectNV() {}
__attribute__((visibility("default"))) void vkCmdCopyMemoryToAccelerationStructureKHR() {}
__attribute__((visibility("default"))) void vkCmdCopyMemoryToImageIndirectNV() {}
__attribute__((visibility("default"))) void vkCmdCopyMemoryToMicromapEXT() {}
__attribute__((visibility("default"))) void vkCmdCopyMicromapEXT() {}
__attribute__((visibility("default"))) void vkCmdCopyMicromapToMemoryEXT() {}
__attribute__((visibility("default"))) void vkCmdCopyTensorARM() {}
__attribute__((visibility("default"))) void vkCmdCuLaunchKernelNVX() {}
__attribute__((visibility("default"))) void vkCmdDebugMarkerBeginEXT() {}
__attribute__((visibility("default"))) void vkCmdDebugMarkerEndEXT() {}
__attribute__((visibility("default"))) void vkCmdDebugMarkerInsertEXT() {}
__attribute__((visibility("default"))) void vkCmdDecodeVideoKHR() {}
__attribute__((visibility("default"))) void vkCmdDecompressMemoryIndirectCountNV() {}
__attribute__((visibility("default"))) void vkCmdDecompressMemoryNV() {}
__attribute__((visibility("default"))) void vkCmdDispatchBaseKHR() {}
__attribute__((visibility("default"))) void vkCmdDispatchDataGraphARM() {}
__attribute__((visibility("default"))) void vkCmdDrawClusterHUAWEI() {}
__attribute__((visibility("default"))) void vkCmdDrawClusterIndirectHUAWEI() {}
__attribute__((visibility("default"))) void vkCmdDrawIndexedIndirectCountAMD() {}
__attribute__((visibility("default"))) void vkCmdDrawIndirectByteCountEXT() {}
__attribute__((visibility("default"))) void vkCmdDrawIndirectCountAMD() {}
__attribute__((visibility("default"))) void vkCmdDrawMeshTasksEXT() {}
__attribute__((visibility("default"))) void vkCmdDrawMeshTasksIndirectCountEXT() {}
__attribute__((visibility("default"))) void vkCmdDrawMeshTasksIndirectCountNV() {}
__attribute__((visibility("default"))) void vkCmdDrawMeshTasksIndirectEXT() {}
__attribute__((visibility("default"))) void vkCmdDrawMeshTasksIndirectNV() {}
__attribute__((visibility("default"))) void vkCmdDrawMeshTasksNV() {}
__attribute__((visibility("default"))) void vkCmdDrawMultiEXT() {}
__attribute__((visibility("default"))) void vkCmdDrawMultiIndexedEXT() {}
__attribute__((visibility("default"))) void vkCmdEncodeVideoKHR() {}
__attribute__((visibility("default"))) void vkCmdEndConditionalRenderingEXT() {}
__attribute__((visibility("default"))) void vkCmdEndQueryIndexedEXT() {}
__attribute__((visibility("default"))) void vkCmdEndTransformFeedbackEXT() {}
__attribute__((visibility("default"))) void vkCmdEndVideoCodingKHR() {}
__attribute__((visibility("default"))) void vkCmdExecuteGeneratedCommandsEXT() {}
__attribute__((visibility("default"))) void vkCmdExecuteGeneratedCommandsNV() {}
__attribute__((visibility("default"))) void vkCmdOpticalFlowExecuteNV() {}
__attribute__((visibility("default"))) void vkCmdPreprocessGeneratedCommandsEXT() {}
__attribute__((visibility("default"))) void vkCmdPreprocessGeneratedCommandsNV() {}
__attribute__((visibility("default"))) void vkCmdPushConstants2() {}
__attribute__((visibility("default"))) void vkCmdPushConstants2KHR() {}
__attribute__((visibility("default"))) void vkCmdPushDescriptorSet2() {}
__attribute__((visibility("default"))) void vkCmdPushDescriptorSet2KHR() {}
__attribute__((visibility("default"))) void vkCmdPushDescriptorSetWithTemplate() {}
__attribute__((visibility("default"))) void vkCmdPushDescriptorSetWithTemplate2() {}
__attribute__((visibility("default"))) void vkCmdPushDescriptorSetWithTemplate2KHR() {}
__attribute__((visibility("default"))) void vkCmdResolveImage2() {}
__attribute__((visibility("default"))) void vkCmdResolveImage2KHR() {}
__attribute__((visibility("default"))) void vkCmdSetAlphaToCoverageEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetAlphaToOneEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetAttachmentFeedbackLoopEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetCheckpointNV() {}
__attribute__((visibility("default"))) void vkCmdSetCoarseSampleOrderNV() {}
__attribute__((visibility("default"))) void vkCmdSetColorBlendAdvancedEXT() {}
__attribute__((visibility("default"))) void vkCmdSetColorWriteEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetConservativeRasterizationModeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetCoverageModulationModeNV() {}
__attribute__((visibility("default"))) void vkCmdSetCoverageModulationTableEnableNV() {}
__attribute__((visibility("default"))) void vkCmdSetCoverageModulationTableNV() {}
__attribute__((visibility("default"))) void vkCmdSetCoverageReductionModeNV() {}
__attribute__((visibility("default"))) void vkCmdSetCoverageToColorEnableNV() {}
__attribute__((visibility("default"))) void vkCmdSetCoverageToColorLocationNV() {}
__attribute__((visibility("default"))) void vkCmdSetDepthClampEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDepthClampRangeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDepthClipEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDepthClipNegativeOneToOneEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDepthCompareOpEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDescriptorBufferOffsets2EXT() {}
__attribute__((visibility("default"))) void vkCmdSetDescriptorBufferOffsetsEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDeviceMaskKHR() {}
__attribute__((visibility("default"))) void vkCmdSetDiscardRectangleEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetDiscardRectangleModeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetExclusiveScissorEnableNV() {}
__attribute__((visibility("default"))) void vkCmdSetExclusiveScissorNV() {}
__attribute__((visibility("default"))) void vkCmdSetExtraPrimitiveOverestimationSizeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetFragmentShadingRateEnumNV() {}
__attribute__((visibility("default"))) void vkCmdSetLineRasterizationModeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetLineStipple() {}
__attribute__((visibility("default"))) void vkCmdSetLineStippleEXT() {}
__attribute__((visibility("default"))) void vkCmdSetLineStippleEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetLineStippleKHR() {}
__attribute__((visibility("default"))) void vkCmdSetLogicOpEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetPatchControlPointsEXT() {}
__attribute__((visibility("default"))) void vkCmdSetPerformanceMarkerINTEL() {}
__attribute__((visibility("default"))) void vkCmdSetPerformanceOverrideINTEL() {}
__attribute__((visibility("default"))) void vkCmdSetPerformanceStreamMarkerINTEL() {}
__attribute__((visibility("default"))) void vkCmdSetPolygonModeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetProvokingVertexModeEXT() {}
__attribute__((visibility("default"))) void vkCmdSetRasterizationSamplesEXT() {}
__attribute__((visibility("default"))) void vkCmdSetRasterizationStreamEXT() {}
__attribute__((visibility("default"))) void vkCmdSetRayTracingPipelineStackSizeKHR() {}
__attribute__((visibility("default"))) void vkCmdSetRenderingAttachmentLocations() {}
__attribute__((visibility("default"))) void vkCmdSetRenderingAttachmentLocationsKHR() {}
__attribute__((visibility("default"))) void vkCmdSetRenderingInputAttachmentIndices() {}
__attribute__((visibility("default"))) void vkCmdSetRenderingInputAttachmentIndicesKHR() {}
__attribute__((visibility("default"))) void vkCmdSetRepresentativeFragmentTestEnableNV() {}
__attribute__((visibility("default"))) void vkCmdSetSampleLocationsEnableEXT() {}
__attribute__((visibility("default"))) void vkCmdSetSampleMaskEXT() {}
__attribute__((visibility("default"))) void vkCmdSetShadingRateImageEnableNV() {}
__attribute__((visibility("default"))) void vkCmdSetStencilOp() {}
__attribute__((visibility("default"))) void vkCmdSetTessellationDomainOriginEXT() {}
__attribute__((visibility("default"))) void vkCmdSetViewportShadingRatePaletteNV() {}
__attribute__((visibility("default"))) void vkCmdSetViewportSwizzleNV() {}
__attribute__((visibility("default"))) void vkCmdSetViewportWScalingEnableNV() {}
__attribute__((visibility("default"))) void vkCmdSetViewportWScalingNV() {}
__attribute__((visibility("default"))) void vkCmdSubpassShadingHUAWEI() {}
__attribute__((visibility("default"))) void vkCmdTraceRaysIndirect2KHR() {}
__attribute__((visibility("default"))) void vkCmdTraceRaysIndirectKHR() {}
__attribute__((visibility("default"))) void vkCmdTraceRaysKHR() {}
__attribute__((visibility("default"))) void vkCmdTraceRaysNV() {}
__attribute__((visibility("default"))) void vkCmdUpdatePipelineIndirectBufferNV() {}
__attribute__((visibility("default"))) void vkCmdWriteAccelerationStructuresPropertiesKHR() {}
__attribute__((visibility("default"))) void vkCmdWriteAccelerationStructuresPropertiesNV() {}
__attribute__((visibility("default"))) void vkCmdWriteBufferMarker2AMD() {}
__attribute__((visibility("default"))) void vkCmdWriteBufferMarkerAMD() {}
__attribute__((visibility("default"))) void vkCmdWriteMicromapsPropertiesEXT() {}
__attribute__((visibility("default"))) void vkCompileDeferredNV() {}
__attribute__((visibility("default"))) void vkConvertCooperativeVectorMatrixNV() {}
__attribute__((visibility("default"))) void vkCopyAccelerationStructureKHR() {}
__attribute__((visibility("default"))) void vkCopyAccelerationStructureToMemoryKHR() {}
__attribute__((visibility("default"))) void vkCopyImageToImage() {}
__attribute__((visibility("default"))) void vkCopyImageToImageEXT() {}
__attribute__((visibility("default"))) void vkCopyImageToMemory() {}
__attribute__((visibility("default"))) void vkCopyImageToMemoryEXT() {}
__attribute__((visibility("default"))) void vkCopyMemoryToAccelerationStructureKHR() {}
__attribute__((visibility("default"))) void vkCopyMemoryToImage() {}
__attribute__((visibility("default"))) void vkCopyMemoryToImageEXT() {}
__attribute__((visibility("default"))) void vkCopyMemoryToMicromapEXT() {}
__attribute__((visibility("default"))) void vkCopyMicromapEXT() {}
__attribute__((visibility("default"))) void vkCopyMicromapToMemoryEXT() {}
__attribute__((visibility("default"))) void vkDeferredOperationJoinKHR() {}
__attribute__((visibility("default"))) void vkDisplayPowerControlEXT() {}
__attribute__((visibility("default"))) void vkEnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM() {}
__attribute__((visibility("default"))) void vkGetAccelerationStructureBuildSizesKHR() {}
__attribute__((visibility("default"))) void vkGetAccelerationStructureDeviceAddressKHR() {}
__attribute__((visibility("default"))) void vkGetAccelerationStructureHandleNV() {}
__attribute__((visibility("default"))) void vkGetAccelerationStructureMemoryRequirementsNV() {}
__attribute__((visibility("default"))) void vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT() {}
__attribute__((visibility("default"))) void vkGetBufferDeviceAddressEXT() {}
__attribute__((visibility("default"))) void vkGetBufferOpaqueCaptureAddressKHR() {}
__attribute__((visibility("default"))) void vkGetBufferOpaqueCaptureDescriptorDataEXT() {}
__attribute__((visibility("default"))) void vkGetCalibratedTimestampsKHR() {}
__attribute__((visibility("default"))) void vkGetDataGraphPipelineAvailablePropertiesARM() {}
__attribute__((visibility("default"))) void vkGetDataGraphPipelinePropertiesARM() {}
__attribute__((visibility("default"))) void vkGetDataGraphPipelineSessionBindPointRequirementsARM() {}
__attribute__((visibility("default"))) void vkGetDataGraphPipelineSessionMemoryRequirementsARM() {}
__attribute__((visibility("default"))) void vkGetDeferredOperationMaxConcurrencyKHR() {}
__attribute__((visibility("default"))) void vkGetDeferredOperationResultKHR() {}
__attribute__((visibility("default"))) void vkGetDescriptorEXT() {}
__attribute__((visibility("default"))) void vkGetDescriptorSetHostMappingVALVE() {}
__attribute__((visibility("default"))) void vkGetDescriptorSetLayoutBindingOffsetEXT() {}
__attribute__((visibility("default"))) void vkGetDescriptorSetLayoutHostMappingInfoVALVE() {}
__attribute__((visibility("default"))) void vkGetDescriptorSetLayoutSizeEXT() {}
__attribute__((visibility("default"))) void vkGetDeviceAccelerationStructureCompatibilityKHR() {}
__attribute__((visibility("default"))) void vkGetDeviceFaultInfoEXT() {}
__attribute__((visibility("default"))) void vkGetDeviceGroupPeerMemoryFeaturesKHR() {}
__attribute__((visibility("default"))) void vkGetDeviceGroupPresentCapabilitiesKHR() {}
__attribute__((visibility("default"))) void vkGetDeviceImageSparseMemoryRequirementsKHR() {}
__attribute__((visibility("default"))) void vkGetDeviceMemoryOpaqueCaptureAddressKHR() {}
__attribute__((visibility("default"))) void vkGetDeviceMicromapCompatibilityEXT() {}
__attribute__((visibility("default"))) void vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI() {}
__attribute__((visibility("default"))) void vkGetDeviceTensorMemoryRequirementsARM() {}
__attribute__((visibility("default"))) void vkGetDynamicRenderingTilePropertiesQCOM() {}
__attribute__((visibility("default"))) void vkGetEncodedVideoSessionParametersKHR() {}
__attribute__((visibility("default"))) void vkGetFenceFdKHR() {}
__attribute__((visibility("default"))) void vkGetFramebufferTilePropertiesQCOM() {}
__attribute__((visibility("default"))) void vkGetGeneratedCommandsMemoryRequirementsEXT() {}
__attribute__((visibility("default"))) void vkGetGeneratedCommandsMemoryRequirementsNV() {}
__attribute__((visibility("default"))) void vkGetImageDrmFormatModifierPropertiesEXT() {}
__attribute__((visibility("default"))) void vkGetImageOpaqueCaptureDescriptorDataEXT() {}
__attribute__((visibility("default"))) void vkGetImageSubresourceLayout2EXT() {}
__attribute__((visibility("default"))) void vkGetImageViewAddressNVX() {}
__attribute__((visibility("default"))) void vkGetImageViewHandle64NVX() {}
__attribute__((visibility("default"))) void vkGetImageViewHandleNVX() {}
__attribute__((visibility("default"))) void vkGetImageViewOpaqueCaptureDescriptorDataEXT() {}
__attribute__((visibility("default"))) void vkGetLatencyTimingsNV() {}
__attribute__((visibility("default"))) void vkGetMemoryFdKHR() {}
__attribute__((visibility("default"))) void vkGetMemoryFdPropertiesKHR() {}
__attribute__((visibility("default"))) void vkGetMemoryHostPointerPropertiesEXT() {}
__attribute__((visibility("default"))) void vkGetMemoryRemoteAddressNV() {}
__attribute__((visibility("default"))) void vkGetMicromapBuildSizesEXT() {}
__attribute__((visibility("default"))) void vkGetPastPresentationTimingGOOGLE() {}
__attribute__((visibility("default"))) void vkGetPerformanceParameterINTEL() {}
__attribute__((visibility("default"))) void vkGetPhysicalDeviceCooperativeVectorPropertiesNV() {}
__attribute__((visibility("default"))) void vkGetPhysicalDeviceExternalTensorPropertiesARM() {}
__attribute__((visibility("default"))) void vkGetPhysicalDeviceQueueFamilyDataGraphProcessingEnginePropertiesARM() {}
__attribute__((visibility("default"))) void vkGetPhysicalDeviceQueueFamilyDataGraphPropertiesARM() {}
__attribute__((visibility("default"))) void vkGetPipelineBinaryDataKHR() {}
__attribute__((visibility("default"))) void vkGetPipelineIndirectDeviceAddressNV() {}
__attribute__((visibility("default"))) void vkGetPipelineIndirectMemoryRequirementsNV() {}
__attribute__((visibility("default"))) void vkGetPipelineKeyKHR() {}
__attribute__((visibility("default"))) void vkGetPipelinePropertiesEXT() {}
__attribute__((visibility("default"))) void vkGetQueueCheckpointData2NV() {}
__attribute__((visibility("default"))) void vkGetQueueCheckpointDataNV() {}
__attribute__((visibility("default"))) void vkGetRayTracingCaptureReplayShaderGroupHandlesKHR() {}
__attribute__((visibility("default"))) void vkGetRayTracingShaderGroupHandlesKHR() {}
__attribute__((visibility("default"))) void vkGetRayTracingShaderGroupHandlesNV() {}
__attribute__((visibility("default"))) void vkGetRayTracingShaderGroupStackSizeKHR() {}
__attribute__((visibility("default"))) void vkGetRefreshCycleDurationGOOGLE() {}
__attribute__((visibility("default"))) void vkGetRenderingAreaGranularity() {}
__attribute__((visibility("default"))) void vkGetRenderingAreaGranularityKHR() {}
__attribute__((visibility("default"))) void vkGetSamplerOpaqueCaptureDescriptorDataEXT() {}
__attribute__((visibility("default"))) void vkGetSemaphoreFdKHR() {}
__attribute__((visibility("default"))) void vkGetShaderBinaryDataEXT() {}
__attribute__((visibility("default"))) void vkGetShaderInfoAMD() {}
__attribute__((visibility("default"))) void vkGetShaderModuleCreateInfoIdentifierEXT() {}
__attribute__((visibility("default"))) void vkGetShaderModuleIdentifierEXT() {}
__attribute__((visibility("default"))) void vkGetSwapchainCounterEXT() {}
__attribute__((visibility("default"))) void vkGetSwapchainStatusKHR() {}
__attribute__((visibility("default"))) void vkGetTensorMemoryRequirementsARM() {}
__attribute__((visibility("default"))) void vkGetTensorOpaqueCaptureDescriptorDataARM() {}
__attribute__((visibility("default"))) void vkGetTensorViewOpaqueCaptureDescriptorDataARM() {}
__attribute__((visibility("default"))) void vkGetValidationCacheDataEXT() {}
__attribute__((visibility("default"))) void vkGetVideoSessionMemoryRequirementsKHR() {}
__attribute__((visibility("default"))) void vkImportFenceFdKHR() {}
__attribute__((visibility("default"))) void vkImportSemaphoreFdKHR() {}
__attribute__((visibility("default"))) void vkInitializePerformanceApiINTEL() {}
__attribute__((visibility("default"))) void vkLatencySleepNV() {}
__attribute__((visibility("default"))) void vkMergeValidationCachesEXT() {}
__attribute__((visibility("default"))) void vkQueueNotifyOutOfBandNV() {}
__attribute__((visibility("default"))) void vkQueueSetPerformanceConfigurationINTEL() {}
__attribute__((visibility("default"))) void vkReleasePerformanceConfigurationINTEL() {}
__attribute__((visibility("default"))) void vkReleaseProfilingLockKHR() {}
__attribute__((visibility("default"))) void vkSetDeviceMemoryPriorityEXT() {}
__attribute__((visibility("default"))) void vkSetHdrMetadataEXT() {}
__attribute__((visibility("default"))) void vkSetLatencyMarkerNV() {}
__attribute__((visibility("default"))) void vkSetLatencySleepModeNV() {}
__attribute__((visibility("default"))) void vkSetLocalDimmingAMD() {}
__attribute__((visibility("default"))) void vkTransitionImageLayout() {}
__attribute__((visibility("default"))) void vkTransitionImageLayoutEXT() {}
__attribute__((visibility("default"))) void vkTrimCommandPoolKHR() {}
__attribute__((visibility("default"))) void vkUninitializePerformanceApiINTEL() {}
__attribute__((visibility("default"))) void vkUpdateDescriptorSetWithTemplateKHR() {}
__attribute__((visibility("default"))) void vkUpdateIndirectExecutionSetPipelineEXT() {}
__attribute__((visibility("default"))) void vkUpdateIndirectExecutionSetShaderEXT() {}
__attribute__((visibility("default"))) void vkUpdateVideoSessionParametersKHR() {}
__attribute__((visibility("default"))) void vkWaitForPresent2KHR() {}
__attribute__((visibility("default"))) void vkWaitForPresentKHR() {}
__attribute__((visibility("default"))) void vkWriteAccelerationStructuresPropertiesKHR() {}
__attribute__((visibility("default"))) void vkWriteMicromapsPropertiesEXT() {}